'use client';
import { useState, useEffect, useRef } from 'react';
const G='#10B981',GD='#059669';
function ZealAvatar({size=36}:{size?:number}){return(<div style={{width:size,height:size,borderRadius:'50%',background:GD,display:'flex',alignItems:'center',justifyContent:'center',flexShrink:0}}><svg width={size*.5} height={size*.5} viewBox="0 0 24 24" fill="#fff"><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z"/></svg></div>);}
function TypingDots(){return(<div style={{display:'flex',gap:4,alignItems:'center',padding:'10px 14px',background:'#1a1a1a',borderRadius:16,borderBottomLeftRadius:4}}>{[0,1,2].map(i=>(<div key={i} style={{width:6,height:6,borderRadius:'50%',background:'#525252',animation:'zealDot 1.2s ease-in-out infinite',animationDelay:`${i*.2}s`}}/>))}</div>);}
function Bubble({text,typing}:{text:string;typing:boolean}){const[d,setD]=useState('');useEffect(()=>{if(typing){let i=0;setD('');const iv=setInterval(()=>{i++;setD(text.slice(0,i));if(i>=text.length)clearInterval(iv);},18);return()=>clearInterval(iv);}else setD(text);},[text,typing]);return(<div style={{background:'#1a1a1a',borderRadius:16,borderBottomLeftRadius:4,padding:'10px 14px',maxWidth:'85%',color:'#e5e5e5',fontSize:14,lineHeight:1.5}}>{d}</div>);}
const STEPS=['Reading through the lesson...','Identifying key concepts...','Crafting your questions...','Almost ready...'];
function ThinkingCard(){const[s,setS]=useState(0);const[p,setP]=useState(0);useEffect(()=>{const si=setInterval(()=>setS(x=>Math.min(x+1,STEPS.length-1)),1200);const pi=setInterval(()=>setP(x=>Math.min(x+1,100)),48);return()=>{clearInterval(si);clearInterval(pi);};},[]);return(<div style={{background:'#1a1a1a',border:'1px solid #2a2a2a',borderRadius:16,padding:'14px 16px',maxWidth:'85%'}}>{STEPS.map((st,i)=>(<div key={i} style={{display:'flex',alignItems:'center',gap:8,marginBottom:6,opacity:i<=s?1:0.2,transition:'opacity 0.4s',fontSize:12,color:i===s?'#fff':'#525252'}}><div style={{width:6,height:6,borderRadius:'50%',background:i<s?G:i===s?GD:'#333',flexShrink:0}}/>{st}</div>))}<div style={{height:2,background:'#222',borderRadius:2,marginTop:10,overflow:'hidden'}}><div style={{height:'100%',background:G,borderRadius:2,width:`${p}%`,transition:'width 0.1s linear'}}/></div></div>);}
export default function ZealQuiz({course}:{course:any}){
const[screen,setScreen]=useState('entry');
const[messages,setMessages]=useState<any[]>([]);
const[questions,setQuestions]=useState<any[]>([]);
const[currentQ,setCurrentQ]=useState(0);
const[selected,setSelected]=useState<string|null>(null);
const[feedback,setFeedback]=useState<string|null>(null);
const[score,setScore]=useState(0);
const[error,setError]=useState('');
const[showThink,setShowThink]=useState(false);
const[showDots,setShowDots]=useState(false);
const ref=useRef<HTMLDivElement>(null);
useEffect(()=>{ref.current?.scrollIntoView({behavior:'smooth'});},[messages,showThink,showDots,selected,feedback]);
const addMsg=(text:string,typing=true):Promise<void>=>new Promise(resolve=>{const id=Math.random().toString(36).slice(2);setShowDots(true);setTimeout(()=>{setShowDots(false);setMessages(m=>[...m,{id,text,typing}]);setTimeout(resolve,typing?text.length*18+400:400);},700);});
const start=async()=>{setScreen('intro');setMessages([]);setError('');await addMsg("Hey — I'm Zeal.");await addMsg("I've gone through this lesson with you. Let me test what actually landed.");await addMsg("5 questions. No tricks. Just tell me what you think and I'll tell you where you stand.");setScreen('thinking');setShowThink(true);await addMsg("Give me a moment...",false);const res=await fetch('/api/ai-quiz',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({courseTitle:course.title,subject:course.subject,level:course.category,subCategory:course.sub_category})});const data=await res.json();if(!data.success){setError('Zeal ran into a problem. Try again.');setScreen('entry');setShowThink(false);return;}setQuestions(data.questions);setShowThink(false);setCurrentQ(0);setSelected(null);setFeedback(null);setScreen('quiz');await addMsg("Here we go.",false);};
const submit=async(letter:string)=>{if(selected)return;setSelected(letter);const q=questions[currentQ];const correct=letter===q.correct;if(correct)setScore(s=>s+1);const res=await fetch('/api/ai-feedback',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({question:q.question,studentAnswer:letter,correctAnswer:q.correct,explanation:q.explanation,subject:course.subject,level:course.category})});const data=await res.json();const msg=data.success?data.feedback:correct?'Exactly right.':'Not quite — but now you know.';setFeedback(msg);await addMsg(msg,true);};
const next=()=>{if(currentQ+1>=questions.length)setScreen('complete');else{setCurrentQ(q=>q+1);setSelected(null);setFeedback(null);}};
const q=questions[currentQ];
const pct=questions.length>0?Math.round((score/questions.length)*100):0;
if(screen==='entry')return(<div><style>{`@keyframes zealDot{0%,80%,100%{transform:scale(0.6);opacity:0.4}40%{transform:scale(1);opacity:1}}`}</style><div style={{display:'flex',flexDirection:'column',alignItems:'center',gap:12,padding:'28px 0'}}><ZealAvatar size={52}/><span style={{fontSize:11,fontWeight:700,letterSpacing:2,color:GD}}>ZEAL</span>{error&&<p style={{fontSize:12,color:'#f87171',textAlign:'center'}}>{error}</p>}<button onClick={start} style={{background:G,color:'#000',border:'none',borderRadius:999,padding:'10px 32px',fontWeight:700,fontSize:14,cursor:'pointer',marginTop:4,minHeight:0,minWidth:0}}>Quiz</button></div></div>);
if(screen==='complete'){const m=pct===100?'Perfect. Every single one.':pct>=80?'Strong work. You know this material.':pct>=60?'Good effort. Review the ones you missed.':'Keep at it — understanding comes with repetition.';return(<div><style>{`@keyframes zealDot{0%,80%,100%{transform:scale(0.6);opacity:0.4}40%{transform:scale(1);opacity:1}}`}</style><div style={{display:'flex',flexDirection:'column',alignItems:'center',gap:12,padding:'28px 0',textAlign:'center'}}><ZealAvatar size={48}/><span style={{fontSize:11,fontWeight:700,letterSpacing:2,color:GD}}>ZEAL</span><div style={{width:80,height:80,borderRadius:'50%',background:pct>=60?'rgba(16,185,129,0.12)':'rgba(239,68,68,0.1)',display:'flex',alignItems:'center',justifyContent:'center',marginTop:8}}><span style={{fontSize:26,fontWeight:800,color:pct>=60?G:'#ef4444'}}>{pct}%</span></div><p style={{fontSize:14,color:'#e5e5e5',maxWidth:260,lineHeight:1.5}}>{m}</p><p style={{fontSize:12,color:'#525252'}}>{score} of {questions.length} correct</p><button onClick={()=>{setScreen('entry');setMessages([]);setScore(0);setError('');setShowThink(false);setShowDots(false);}} style={{background:G,color:'#000',border:'none',borderRadius:999,padding:'10px 32px',fontWeight:700,fontSize:14,cursor:'pointer',marginTop:8,minHeight:0,minWidth:0}}>Try again</button></div></div>);}
return(<div style={{paddingTop:8}}><style>{`@keyframes zealDot{0%,80%,100%{transform:scale(0.6);opacity:0.4}40%{transform:scale(1);opacity:1}}`}</style><div style={{display:'flex',flexDirection:'column',gap:12}}>{messages.map((msg:any)=>(<div key={msg.id} style={{display:'flex',alignItems:'flex-end',gap:8}}><ZealAvatar size={28}/><Bubble text={msg.text} typing={msg.typing}/></div>))}{showDots&&(<div style={{display:'flex',alignItems:'flex-end',gap:8}}><ZealAvatar size={28}/><TypingDots/></div>)}{showThink&&(<div style={{display:'flex',alignItems:'flex-start',gap:8}}><ZealAvatar size={28}/><ThinkingCard/></div>)}{screen==='quiz'&&q&&(<div style={{marginTop:4}}><div style={{display:'flex',justifyContent:'space-between',fontSize:11,color:'#525252',marginBottom:6}}><span>Question {currentQ+1} of {questions.length}</span><span style={{color:G}}>Score: {score}</span></div><div style={{height:2,background:'#222',borderRadius:2,marginBottom:14,overflow:'hidden'}}><div style={{height:'100%',background:G,width:`${(currentQ/questions.length)*100}%`,borderRadius:2}}/></div><div style={{background:'#1a1a1a',border:'1px solid #2a2a2a',borderRadius:16,padding:16}}><p style={{fontSize:14,fontWeight:700,color:'#fff',lineHeight:1.5,marginBottom:14}}>{q.question}</p><div style={{display:'flex',flexDirection:'column',gap:8}}>{q.options.map((opt:string)=>{const letter=opt.charAt(0);const isSel=selected===letter;const isRight=selected!==null&&letter===q.correct;const isWrong=selected!==null&&isSel&&!isRight;let bg='#222',border='#333',color='#e5e5e5';if(isRight){bg='rgba(16,185,129,0.15)';border=G;color='#34d399';}else if(isWrong){bg='rgba(239,68,68,0.12)';border='#ef4444';color='#f87171';}else if(isSel){bg='rgba(16,185,129,0.08)';border=G;}return(<button key={opt} onClick={()=>submit(letter)} disabled={!!selected} style={{background:bg,border:`1px solid ${border}`,borderRadius:12,padding:'10px 14px',textAlign:'left',fontSize:13,color,cursor:selected?'default':'pointer',transition:'all 0.2s',minHeight:0,minWidth:0,width:'100%'}}>{opt}</button>);})}</div>{feedback!==null&&(<button onClick={next} style={{width:'100%',marginTop:14,background:G,color:'#000',border:'none',borderRadius:12,padding:12,fontWeight:700,fontSize:14,cursor:'pointer',minHeight:0}}>{currentQ+1>=questions.length?'See results':'Next question →'}</button>)}</div></div>)}<div ref={ref}/></div></div>);
}
